#cloud-config
autoinstall:
  version: 1

  locale: es_ES.UTF-8

  keyboard:
    layout: es
    variant: ""

  timezone: Europe/Madrid

  identity:
    hostname: ubuntu
    username: usuario
    password: "$6$ubuntu$cvdRho/9jgxhsrjommOy/VhcdhpXAcYEGnHB13FtYrTJtJ79eGY2k9hRGzBPVXFV6aE/66AKBBbTL4/Dt9K6J1"

  storage:
    layout:
      name: direct

  packages: []

  ssh:
    install-server: false

  shutdown: poweroff
